### PR TITLE
Disable w503 and update to version 0.2.3 

### PR DESCRIPTION
**Pull request by will-Do**

### CODE REVIEW

**Comment by will-Do** [comment]
Recently a new merged file in avocado-vt introduced a W503 complain that 'line break before binary operator', and then all the follow PRs are failed on Travis CI build. But We do should disable it by default. A refer from PEP8:
https://www.python.org/dev/peps/pep-0008/#should-a-line-break-before-or-after-a-binary-operator

**Comment by will-Do** [comment]
@lmr 
Please help to review and merge this PR, thanks.

**Comment by ldoktor** [comment]
Well the proper fix would be to address those issues in avocado-vt sources, wouldn't it? We already did this in Avocado and it is fairly simple change which improves the readability.

As a temporary fix I could recommend using `inspekt --disable E501,E265,W503,W601,E402` in your check script.

**Comment by will-Do** [comment]
@ldoktor 
Yes, I tried to address the in avocado-vt first, but after do some search, I think W503 should be disabled, you can check the commit message of the first patch.

**Comment by will-Do** [comment]
BTW, Travis CI just run 'make check', and the script we should update it selftests/checkall, I don't think it is the right or temporary way to fix this problem.

**Comment by ldoktor** [comment]
I think it is as `avocado` uses custom setting as well (we ignore naked Exceptions). Anyway I'd be against, but you might convince other maintainers... (my goal would be to disable all of them except the bare minimum)

**Comment by ldoktor** [comment]
https://github.com/avocado-framework/avocado/blob/master/selftests/checkall

**Comment by will-Do** [comment]
Guess you just convinced me :)
The main propose of this fix is disable W503, and if you agree with that, I will close this one and raise a new PR for avocado-vt.
BTW, just think about your goal and I agree with it, let the checker do his own job and custom setting for each project who using it.

**Comment by ldoktor** [comment]
OK, thanks, closing this PR.

**Comment by ldoktor** [comment]
OK I'm sorry for denying this. After re-reading the topic I believe this could be applied without the version increase as it's not necessary needed. (basically the W503 is disabled by default on newer versions, but some older versions keep enforcing it)

**Pull request closed without merging**
